name: Requisite Check
run-name: Requisite Check
on: 
    pull_request: 
        types: [opened]
        paths: 'projects/**'

jobs:
  Requisite-Check:
    name: Check for files
    runs-on: ubuntu-latest
    steps:
        - name: Check out
          uses: actions/checkout@v2

        - name: Testing
          run: node .github/index.js