name: Gerbview Comment
run-name: Gerbview Comment
on: 
    pull_request: 
        #types: [opened]
        paths: 'projects/**'

jobs:
  echo-input:
    #if: ${{ github.event.label.name == 'Submission' }}
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.ORPHEUS_PAT || secrets.GITHUB_TOKEN }}
          script: |
            const script = require('./.github/index.js')
            console.log(await script({gh: github, ctx: context}))